### ISSUE TITLE
Service does not restart after a reboot

### ISSUE THREAD

**Issue by joseph-kimberley** [mrlesmithjr/ansible-prometheus-node-exporter#4]
The `node_exporter` service does not restart after a machine reboot.

Needs to be an option to set `enabled: yes` in the `systemd` ansible task:

    - name: restart node_exporter
      service:
        name: "node_exporter"
        state: "restarted"
        enabled: yes     # This can be templated
      become: true

**Comment by mrlesmithjr** [comment]
Done! Thanks for reporting.
